# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Database-Schema-Verification
version:      1.01
version_from: lib/Database/Schema/Verification.pm
installdirs:  site
requires:
    MIME::Lite:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
